# Generated by Django 5.2.11 on 2026-02-27 15:00

import django.db.models.deletion
import utils.photo_save
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Area Name')),
            ],
            options={
                'verbose_name': 'Area',
                'verbose_name_plural': 'Areas',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Category Name')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='City Name')),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Metro Name')),
            ],
            options={
                'verbose_name': 'Metro',
                'verbose_name_plural': 'Metros',
            },
        ),
        migrations.CreateModel(
            name='PropertySource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(max_length=100)),
                ('source_url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Sight Name')),
            ],
            options={
                'verbose_name': 'Sight',
                'verbose_name_plural': 'Sights',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Street Name')),
            ],
            options={
                'verbose_name': 'Street',
                'verbose_name_plural': 'Streets',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Location Name')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='properties.area', verbose_name='Area')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='properties.metro', verbose_name='Metro')),
                ('sight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='properties.sight', verbose_name='Sight')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streets', to='properties.street', verbose_name='Street')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Property URL')),
                ('title', models.CharField(max_length=255, verbose_name='Property Title')),
                ('description', models.TextField(verbose_name='Property Description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Property Price')),
                ('room_count', models.IntegerField(verbose_name='Room Count')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Is Sale?')),
                ('is_rent', models.BooleanField(default=False, verbose_name='Is Rent?')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Property Image')),
                ('square', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Property Area')),
                ('document_type', models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Type')),
                ('is_documented', models.BooleanField(default=False, verbose_name='Documented?')),
                ('have_things', models.BooleanField(default=False, verbose_name='Have things?')),
                ('renovation', models.BooleanField(default=False, verbose_name='Renovation?')),
                ('communal', models.BooleanField(default=False, verbose_name='Communal?')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
                ('propertyist_phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Propertyist Phone')),
                ('propertyist_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Propertyist Name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.category', verbose_name='Preferred Category')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties', to='properties.location', verbose_name='Property Location')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.propertysource', verbose_name='Property Source')),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Property Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sent', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notification_type', models.CharField(max_length=50)),
                ('retry_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('also_send_to_customer', models.BooleanField(default=False)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='properties.property')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'indexes': [models.Index(fields=['account'], name='properties__account_e5f76a_idx'), models.Index(fields=['property'], name='properties__propert_97497a_idx'), models.Index(fields=['is_sent'], name='properties__is_sent_518d75_idx'), models.Index(fields=['sent_at'], name='properties__sent_at_93a64a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['price'], name='properties__price_32e7c2_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['room_count'], name='properties__room_co_0b8c20_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_sale'], name='properties__is_sale_0e2b59_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['created_at'], name='properties__created_72ecc3_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['location'], name='properties__locatio_c0eebe_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['category'], name='properties__categor_837604_idx'),
        ),
        migrations.AddIndex(
            model_name='property',
            index=models.Index(fields=['is_rent'], name='properties__is_rent_272692_idx'),
        ),
    ]
