# Generated by Django 5.2.11 on 2026-02-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='also_sendto_customer',
            field=models.BooleanField(default=False),
        ),
    ]
