# Generated by Django 5.2.11 on 2026-02-25 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_notification_also_sendto_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='location_area',
        ),
    ]
