# Generated by Django 5.2.11 on 2026-02-25 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_remove_property_location_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyist_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Propertyist Phone'),
        ),
    ]
