# Generated by Django 5.2.11 on 2026-02-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_propertyist_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='document_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document Type'),
        ),
    ]
