# Generated by Django 5.2.11 on 2026-02-25 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0005_property_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='properties', to='properties.propertysource', verbose_name='Property Source'),
        ),
    ]
