# Generated by Django 5.2.11 on 2026-02-25 14:39

import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_alter_property_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Property Image'),
        ),
    ]
