# Generated by Django 5.2.11 on 2026-02-26 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0007_property_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='also_sendto_customer',
            new_name='also_send_to_customer',
        ),
    ]
