# Generated by Django 5.2.11 on 2026-02-26 07:17

import django.db.models.deletion
import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_rename_also_sendto_customer_notification_also_send_to_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Property Image')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='properties.property', verbose_name='Property')),
            ],
            options={
                'verbose_name': 'Property Image',
                'verbose_name_plural': 'Property Images',
            },
        ),
    ]
