# Generated by Django 5.2.11 on 2026-02-26 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_propertyimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='property_area',
            new_name='square',
        ),
    ]
