# Generated by Django 5.2.11 on 2026-02-26 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_rename_property_area_property_square'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Property URL'),
        ),
    ]
