# Generated by Django 5.2.11 on 2026-02-26 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0011_property_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='renovation',
            field=models.BooleanField(default=False, verbose_name='Renovation?'),
        ),
    ]
