# Generated by Django 5.2.11 on 2026-02-26 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_property_renovation'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='propertyist_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Propertyist Name'),
        ),
    ]
