# Generated by Django 5.2.11 on 2026-02-23 07:53

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCustomerPreferries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Area')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Area')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Price')),
                ('room_count', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5+')], default=1, null=True, verbose_name='Room Count')),
                ('want_rent', models.BooleanField(default=False, verbose_name='Looking for rent?')),
                ('want_sale', models.BooleanField(default=False, verbose_name='Looking for sale?')),
                ('is_documented', models.BooleanField(default=False, verbose_name='Documented?')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('have_things', models.BooleanField(default=False, verbose_name='Have things?')),
                ('communal', models.BooleanField(default=False, verbose_name='Communal?')),
                ('floor', models.IntegerField(blank=True, null=True, verbose_name='Floor')),
            ],
            options={
                'verbose_name': 'Account Customer Preferry',
                'verbose_name_plural': 'Account Customer Preferries',
            },
        ),
        migrations.CreateModel(
            name='AccountCustomers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Customer Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Customer Email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Customer Phone')),
                ('telegram_username', models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Telegram Username')),
            ],
            options={
                'verbose_name': 'Account Customer',
                'verbose_name_plural': 'Account Customers',
            },
        ),
        migrations.CreateModel(
            name='AccountFilters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Filter Name')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Minimum Price')),
                ('max_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Maximum Price')),
                ('min_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minimum Area')),
                ('max_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maximum Area')),
                ('room_count', models.IntegerField(blank=True, null=True, verbose_name='Room Count')),
                ('is_sale', models.BooleanField(default=False, verbose_name='Is Sale?')),
                ('is_rent', models.BooleanField(default=False, verbose_name='Is Rent?')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Account Filter',
                'verbose_name_plural': 'Account Filters',
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Plan Name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Plan Price')),
                ('duration_days', models.IntegerField(verbose_name='Plan Duration (days)')),
                ('max_notifications', models.IntegerField(verbose_name='Maximum Notifications')),
            ],
            options={
                'verbose_name': 'Plan',
                'verbose_name_plural': 'Plans',
            },
        ),
        migrations.CreateModel(
            name='PreferryPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_location', models.IntegerField(default=40)),
                ('weight_price', models.IntegerField(default=30)),
                ('weight_room', models.IntegerField(default=20)),
                ('weight_category', models.IntegerField(default=10)),
            ],
            options={
                'verbose_name': 'Preferry Priority',
                'verbose_name_plural': 'Preferry Priorities',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('image', models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Profile photo')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Phone number')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('city', models.CharField(blank=True, max_length=100, null=True, verbose_name='City')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, null=True, verbose_name='Gender')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='About')),
                ('otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='Email Verification OTP')),
                ('reset_password_otp', models.CharField(blank=True, max_length=6, null=True, verbose_name='Password Reset OTP')),
                ('is_reset_password_otp_verified', models.BooleanField(default=False, verbose_name="'Forgot Password' OTP Verified?")),
                ('reset_password_request_count', models.IntegerField(default=0, verbose_name='Number of password reset requests in a day')),
                ('last_reset_password_request_date', models.DateField(blank=True, null=True, verbose_name='Last password reset request date')),
                ('last_password_reset_date', models.DateField(blank=True, null=True, verbose_name='Last password reset date')),
                ('reset_password_otp_created_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Reset OTP creation time')),
                ('reset_password_otp_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Password Reset OTP expiration time')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified?')),
                ('private_account', models.BooleanField(default=False, verbose_name='Private Account?')),
                ('rank', models.IntegerField(default=0, verbose_name='User Rank')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
