# Generated by Django 5.2.11 on 2026-02-23 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomerpreferries',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_preferries', to='properties.category', verbose_name='Preferred Category'),
        ),
        migrations.AddField(
            model_name='accountcustomerpreferries',
            name='location',
            field=models.ManyToManyField(blank=True, related_name='customer_preferries', to='properties.location', verbose_name='Preferred Location'),
        ),
        migrations.AddField(
            model_name='accountcustomers',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountcustomerpreferries',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferries', to='accounts.accountcustomers'),
        ),
        migrations.AddField(
            model_name='accountfilters',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filters', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountfilters',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='account_filters', to='properties.category', verbose_name='Filter Category'),
        ),
        migrations.AddField(
            model_name='accountfilters',
            name='location',
            field=models.ManyToManyField(related_name='account_filters', to='properties.location', verbose_name='Filter Location'),
        ),
        migrations.AddField(
            model_name='preferrypriority',
            name='preferry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.accountcustomerpreferries'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subscription',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.plan'),
        ),
    ]
