# Generated by Django 5.2.11 on 2026-02-23 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('properties', '0002_notification_also_sendto_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountfilters',
            name='account_customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='filters', to='accounts.accountcustomers'),
        ),
        migrations.CreateModel(
            name='AccountFilterMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('account_filter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='accounts.accountfilters')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='filter_matches', to='properties.property')),
            ],
            options={
                'verbose_name': 'Account Filter Match',
                'verbose_name_plural': 'Account Filter Matches',
            },
        ),
    ]
