# Generated by Django 5.2.11 on 2026-02-24 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accountfilters_account_customer_accountfiltermatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='OTP creation time'),
        ),
    ]
