# Generated by Django 5.2.11 on 2026-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomers',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True,
                verbose_name='Customer Created Date'
            ),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('undefined', 'Undefined')], default='undefined', max_length=10, null=True, verbose_name='Gender'),
        ),
    ]
