# Generated by Django 5.2.11 on 2026-02-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accountcustomers_created_at_alter_account_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustomers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Customer Created Date'),
        ),
    ]
