# Generated by Django 5.2.11 on 2026-02-24 14:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountcustomers_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountcustomers',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Customer Created Date'),
            preserve_default=False,
        ),
    ]
