# Generated by Django 5.2.11 on 2026-02-25 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_accountcustomers_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomers',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('undefined', 'Undefined')], default='undefined', max_length=10, null=True, verbose_name='Customer Gender'),
        ),
    ]
