# Generated by Django 5.2.11 on 2026-02-25 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_accountcustomers_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomers',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Customer Address'),
        ),
    ]
