# Generated by Django 5.2.11 on 2026-02-25 09:15

import utils.photo_save
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.photo_save.logo_dir_path, verbose_name='Cover photo'),
        ),
    ]
