# Generated by Django 5.2.11 on 2026-02-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_account_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountcustomerpreferries',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AddField(
            model_name='accountcustomers',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AddField(
            model_name='accountfilters',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AddField(
            model_name='plan',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
        migrations.AddField(
            model_name='preferrypriority',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='Deleted?'),
        ),
    ]
