# Generated by Django 5.2.11 on 2026-02-26 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_accountcustomerpreferries_is_deleted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='balance', to=settings.AUTH_USER_MODEL),
        ),
    ]
