# Generated by Django 5.2.11 on 2026-02-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_accountpayments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountpayments',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Account Payment', 'verbose_name_plural': 'Account Payments'},
        ),
        migrations.AddField(
            model_name='accountpayments',
            name='action_type',
            field=models.CharField(choices=[('subscription', 'Subscription Payment'), ('balance_topup', 'Balance Top-up')], default='subscription', max_length=20),
        ),
        migrations.AddField(
            model_name='accountpayments',
            name='payment_source',
            field=models.CharField(choices=[('card', 'Card'), ('wallet', 'Wallet')], default='card', max_length=10),
        ),
    ]
